# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - ms-ocr-fastapi-docker

on:
  push:
    branches:
      - main2
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_3ac7d096cf0246339277a2b66c17ea51 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_cb0b9633636e4c3fba1f573610cd335a }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_3ac7d096cf0246339277a2b66c17ea51 }}/appsvc/staticsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'ms-ocr-fastapi-docker'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_838fa2964ea64593b19df987ab4d7d48 }}
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_3ac7d096cf0246339277a2b66c17ea51 }}/appsvc/staticsite:${{ github.sha }}'